/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// lib/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ForbiddenLandsCharacterSheet
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// lib/Models/Creature.ts
var Creature = class {
  constructor() {
    this.Id = "";
    this.Name = "";
    this.MaxStamina = 0;
    this.CurrentStamina = 0;
    this.HasActed = false;
    this.IsHero = false;
  }
  isBloodied() {
    return this.CurrentStamina <= Math.ceil(this.MaxStamina / 2);
  }
};

// lib/Models/Constants.ts
var INITIATIVE_VIEW = "initiative-view";
var yes = "Yes";
var no = "No";
var red = "red";
var green = "green";
var orange = "orange";
var centered = "Centered";
var group = "group";
var groupHeader = "groupHeader";
var trackerRowTableStyle = "trackerRowTableStyle";
var leftAlign = "leftAlign";
var fullScreen = "fullScreen";
var paddingLeft5 = "p-left-5";
var height25 = "height25";
var eightyPercentWidth = "eightyPercentWidth";
var twentyPercentWidth = "twentyPercentWidth";
var flex = "flex";

// lib/Views/InitiativeTrackerView.ts
var import_obsidian = require("obsidian");

// lib/Behaviors/TextInputBehaviors.ts
function NumbersOnly(ev) {
  if (!(ev.code.contains("Digit") || ev.code.contains("Backspace"))) {
    ev.preventDefault();
  }
}

// lib/Views/InitiativeTrackerView.ts
var InitiativeView = class extends import_obsidian.ItemView {
  constructor(leaf, app, villains, heroes) {
    super(leaf);
    this.villains = [];
    this.heroes = [];
    this.buttons = [];
    this.round = 1;
    this.app = app;
    if (villains != null && villains.length > -1) {
      villains.forEach((creature) => this.villains.push(creature));
    }
    if (heroes != null && heroes.length > -1) {
      heroes.forEach((creature) => this.heroes.push(creature));
    }
  }
  getViewType() {
    return INITIATIVE_VIEW;
  }
  getDisplayText() {
    return "Initiative tracker";
  }
  getIcon() {
    return "scroll-text";
  }
  async onOpen() {
    this.contentEl.empty();
    this.gridEl = this.contentEl.createDiv();
    this.createInputSection();
    this.createTable(true);
    this.createTable(false);
  }
  async onClose() {
  }
  /***
   * Creates the input section seen at the top of the Initiative Tracker.
   */
  createInputSection() {
    this.formEl = this.gridEl.createDiv({ cls: "fullScreen" });
    this.createTextInput(this.nameInput = new import_obsidian.TextComponent(this.formEl), "Name", false);
    this.createTextInput(this.staminaInput = new import_obsidian.TextComponent(this.formEl), "Max stamina", false);
    this.createTextInput(this.minionStaminaInput = new import_obsidian.TextComponent(this.formEl), "Minion stamina", true);
    let minionCount = { "1": "1", "2": "2", "3": "3", "4": "4", "5": "5", "6": "6", "7": "7", "8": "8" };
    this.minionCountInput = new import_obsidian.DropdownComponent(this.formEl).addOptions(minionCount);
    this.minionCountInput.selectEl.title = "Minion count";
    this.minionCountInput.selectEl.addClass("padded-input");
    this.minionCountInput.selectEl.hidden = true;
    this.typeInput = new import_obsidian.DropdownComponent(this.formEl).addOption("Hero" /* Hero */.toString(), "Hero" /* Hero */.toString()).addOption("Minion" /* Minion */.toString(), "Minion" /* Minion */.toString()).addOption("Horde" /* Horde */.toString(), "Horde" /* Horde */.toString()).addOption("Platoon" /* Platoon */.toString(), "Platoon" /* Platoon */.toString()).addOption("Elite" /* Elite */.toString(), "Elite" /* Elite */.toString()).addOption("Leader" /* Leader */.toString(), "Leader" /* Leader */.toString()).addOption("Solo" /* Solo */.toString(), "Solo" /* Solo */.toString()).onChange((value) => {
      if (value == "Minion" /* Minion */.toString()) {
        this.minionStaminaInput.inputEl.hidden = false;
        this.minionCountInput.selectEl.hidden = false;
        this.staminaInput.inputEl.hidden = true;
      } else {
        this.minionStaminaInput.inputEl.hidden = true;
        this.minionCountInput.selectEl.hidden = true;
        this.staminaInput.inputEl.hidden = false;
      }
    });
    this.typeInput.selectEl.addClass("padded-input");
    this.setInputButtonComponent(new import_obsidian.ButtonComponent(this.formEl), "Hero", () => this.createCreatureRow(void 0, true));
    this.setInputButtonComponent(new import_obsidian.ButtonComponent(this.formEl), "Villain", () => this.createCreatureRow(void 0, false));
    this.createRoundSection();
  }
  setInputButtonComponent(component, text, callback) {
    component.setButtonText(text);
    component.setClass("padded-input");
    component.onClick(callback);
  }
  createTextInput(component, placeHolder, isHidden) {
    component.setPlaceholder(placeHolder);
    component.inputEl.addClasses(["padded-input", "minthirdWidth"]);
    component.inputEl.hidden = isHidden;
  }
  createRoundSection() {
    this.roundEl = this.gridEl.createDiv({ cls: "tableStyle " });
    this.setRound(1);
    this.setMalice(1 + this.heroes.length);
  }
  setMalice(malice, div) {
    var _a;
    this.malice = malice;
    this.maliceEl = (_a = this.maliceEl) != null ? _a : this.roundEl.createDiv({ cls: "rightAlign maliceHeader" });
    this.maliceEl.setText("Malice: " + this.malice);
    let minusMalice = new import_obsidian.ButtonComponent(this.maliceEl);
    minusMalice.setButtonText("-1");
    minusMalice.setClass("headerButtonLeft");
    minusMalice.onClick(() => {
      this.malice--;
      this.setMalice(this.malice, this.maliceEl);
    });
    let plusMalice = new import_obsidian.ButtonComponent(this.maliceEl);
    plusMalice.setButtonText("+1");
    plusMalice.setClass("headerButtonLeft");
    plusMalice.onClick(() => {
      this.malice++;
      this.setMalice(this.malice, this.maliceEl);
    });
  }
  setRound(round, div) {
    this.round = round;
    div = div != null ? div : this.roundEl.createDiv({ cls: "leftAlign roundHeader" });
    div.setText("Round: " + this.round);
    let newRoundButton = new import_obsidian.ButtonComponent(div);
    newRoundButton.setButtonText("New");
    newRoundButton.setClass("headerButtonLeft");
    newRoundButton.onClick(() => {
      if (div != void 0)
        this.newRound(div);
    });
    let resetRoundsButton = new import_obsidian.ButtonComponent(div);
    resetRoundsButton.setButtonText("Reset");
    resetRoundsButton.setClass("headerButtonLeft");
    resetRoundsButton.onClick(() => {
      this.round == 1;
      this.setRound(1, div);
      this.resetActed();
    });
  }
  //Create a HTML Table
  createTable(isHero) {
    let classes = centered + (isHero ? " heroes" : " villains") + " trackerTableStyle fiveTopAndBottomMargin";
    if (isHero) {
      this.heroesTableEl = this.gridEl.createEl("table", { cls: classes });
    } else {
      this.villainsTableEl = this.gridEl.createEl("table", { cls: classes });
    }
    let header = isHero ? this.heroesTableEl.createEl("tr", { cls: "tableHeaderHeight" }) : this.villainsTableEl.createEl("tr", { cls: "tableHeaderHeight" });
    let titleCell = header.createEl("th", { cls: `${eightyPercentWidth} leftAlign` });
    isHero ? titleCell.createEl("h4", { text: "Heroes", cls: "noPaddingNoMargin" }) : titleCell.createEl("h4", { text: "Villains", cls: "noPaddingNoMargin" });
    let createButtonHeader = header.createEl("th", { cls: `${twentyPercentWidth} ${flex}` });
    let resetButtonComp = new import_obsidian.ExtraButtonComponent(createButtonHeader);
    resetButtonComp.extraSettingsEl.setText("Clear");
    resetButtonComp.extraSettingsEl.addClasses(["headerButtonRight", "fullFill", "interactiveColor"]);
    if (isHero) {
      resetButtonComp.onClick(() => {
        this.clearHeroesTable();
      });
    } else {
      resetButtonComp.onClick(() => {
        this.clearVillainsTable();
      });
    }
    if (isHero && this.heroes.length > -1) {
      this.heroes.forEach((creature) => this.createCreatureRow(creature, isHero));
    } else if (!isHero && this.villains.length > -1) {
      this.villains.forEach((creature) => this.createCreatureRow(creature, isHero));
    }
  }
  createGroupRow(table) {
    let groupRow = table.createEl("tr").createDiv();
    groupRow.ondragover = (e) => {
      e.preventDefault();
    };
    groupRow.ondrop = this.groupRowDrop;
    let groupTable = groupRow.createEl("table");
    groupTable.addClasses([group, trackerRowTableStyle, centered, leftAlign, fullScreen]);
    let groupHeader2 = groupTable.createEl("tr", { cls: `${groupHeader}` });
    groupHeader2.createEl("th", { text: "Group", cls: `${paddingLeft5} ninetyPercentWidth` });
    var actButton = new import_obsidian.ExtraButtonComponent(groupHeader2.createEl("th"));
    actButton.extraSettingsEl.setText("ACT");
    actButton.extraSettingsEl.addClasses([".tenPercentWidth", "headerButtonRight", height25]);
    groupTable.createEl("tr");
  }
  groupRowDrop(e) {
    var _a;
    e.preventDefault();
    let data = (_a = e.dataTransfer) == null ? void 0 : _a.getData("text");
    let creature;
    if (data === "String") {
      creature = JSON.parse(data);
      this.createCreatureRow(creature, creature.IsHero);
    }
  }
  createCreatureObject(isHero) {
    let creature = new Creature();
    creature.Id = isHero ? (this.heroes.length + 1).toString() : (this.villains.length + 1).toString();
    creature.Name = this.nameInput.getValue();
    creature.Type = this.typeInput.getValue();
    if (creature.Type == "Minion" /* Minion */) {
      creature.MinionStamina = +this.minionStaminaInput.getValue();
      creature.MinionCount = +this.minionCountInput.getValue();
      creature.MaxStamina = creature.MinionStamina * creature.MinionCount;
    } else {
      creature.MaxStamina = this.staminaInput.getValue != void 0 ? +this.staminaInput.getValue() : 0;
    }
    creature.CurrentStamina = creature.MaxStamina;
  }
  createCreatureRow(creature = new Creature(), isHero) {
    var _a;
    if (creature.Name == "") {
      if (this.nameInput.getValue() == "") {
        return;
      }
      creature.Id = isHero ? (this.heroes.length + 1).toString() : (this.villains.length + 1).toString();
      creature.Name = this.nameInput.getValue();
      this.nameInput.setValue("");
      creature.Type = this.typeInput.getValue();
      if (creature.Type == "Minion" /* Minion */) {
        creature.MinionStamina = +this.minionStaminaInput.getValue();
        this.minionStaminaInput.setValue("");
        creature.MinionCount = +this.minionCountInput.getValue();
        this.minionCountInput.setValue("1");
        creature.MaxStamina = creature.MinionStamina * creature.MinionCount;
      } else {
        creature.MaxStamina = this.staminaInput.getValue != void 0 ? +this.staminaInput.getValue() : 0;
      }
      creature.IsHero = isHero;
      this.staminaInput.setValue("");
    }
    creature.CurrentStamina = creature.MaxStamina;
    try {
      if (isHero && !this.heroes.contains(creature)) {
        this.heroes.push(creature);
      }
      if (!isHero && !this.villains.contains(creature)) {
        this.villains.push(creature);
      }
      let row = isHero ? this.heroesTableEl.createEl("tr", { cls: centered }) : this.villainsTableEl.createEl("tr", { cls: centered });
      row.draggable = true;
      row.ondragstart = (e) => this.onHeroTableRowDragStart(e, creature);
      row.ondragend = (e) => this.onHeroTableRowDragEnd(e);
      row.ondragenter = (e) => this.onHeroTableRowDragEnter(e, this.heroes.indexOf(creature));
      row.id = isHero ? "Hero " + this.heroes.indexOf(creature) : "Villain " + this.villains.indexOf(creature);
      let tableCell = row.createEl("td", { attr: { "colspan": 2 } });
      let tempTable = tableCell.createEl("table", { cls: "fullScreen trackerRowTableStyle" });
      let tempHeader = tempTable.createEl("tr");
      tempHeader.createEl("th", { text: "Name", cls: "trackerTableCellStyle tenRadiusTopLeft" });
      tempHeader.createEl("th", { text: "Stamina", cls: "trackerTableCellStyle" });
      tempHeader.createEl("th", { text: "FTA", cls: "trackerTableCellStyle" });
      tempHeader.createEl("th", { text: "Acted", cls: "trackerTableCellStyle" });
      tempHeader.createEl("th", { text: "", cls: "trackerTableCellStyle tenRadiusTopRight" });
      let tempRow = tempTable.createEl("tr");
      tempRow.id = row.id;
      let nameCell = tempRow.createEl("td", { cls: "Centered name-Cell trackerTableNameCellStyle" });
      let nameTable = nameCell.createDiv({ cls: "tableStyle" });
      let nameRow = nameTable.createDiv({ cls: "tableRowStyle" });
      let creatureType = nameRow.createDiv({ text: (_a = creature.Type) == null ? void 0 : _a.toString(), cls: "verticalType topAlign" });
      creatureType.setAttribute("rowspan", "2");
      nameRow.createDiv({ text: creature.Name, cls: "tableCell fullWidth" });
      let renameField = new import_obsidian.TextComponent(nameRow);
      let renameid = "rename" + (isHero ? "Hero " + this.heroes.indexOf(creature) : "Villain " + this.villains.indexOf(creature));
      renameField.inputEl.id = renameid;
      renameField.setValue(creature.Name);
      renameField.inputEl.hidden = true;
      renameField.inputEl.addClass("fullWidth");
      renameField.inputEl.addClass(centered);
      renameField.inputEl.addClass("fontFifteen");
      let changeNameButton = new import_obsidian.ExtraButtonComponent(nameRow).setIcon("pencil-line").setTooltip("Rename");
      changeNameButton.onClick(() => this.allowRename(nameRow, renameid));
      changeNameButton.extraSettingsEl.addClass("rightAlign");
      changeNameButton.extraSettingsEl.addClass("tableCell");
      changeNameButton.extraSettingsEl.addClass("renameButton");
      let nameCellDiv = nameCell.createDiv({ cls: "condition-buttons" });
      let button1 = new import_obsidian.ExtraButtonComponent(nameCellDiv).setIcon("droplet").setTooltip("Bleeding");
      button1.onClick(() => this.toggleColors(button1));
      let button2 = new import_obsidian.ExtraButtonComponent(nameCellDiv).setIcon("sparkles").setTooltip("Dazed");
      button2.onClick(() => this.toggleColors(button2));
      let button3 = new import_obsidian.ExtraButtonComponent(nameCellDiv).setIcon("frown").setTooltip("Frightened");
      button3.onClick(() => this.toggleColors(button3));
      let button4 = new import_obsidian.ExtraButtonComponent(nameCellDiv).setIcon("grab").setTooltip("Grabbed");
      button4.onClick(() => this.toggleColors(button4));
      let button5 = new import_obsidian.ExtraButtonComponent(nameCellDiv).setIcon("arrow-down-to-line").setTooltip("Prone");
      button5.onClick(() => this.toggleColors(button5));
      let button6 = new import_obsidian.ExtraButtonComponent(nameCellDiv).setIcon("link").setTooltip("Restrained");
      button6.onClick(() => this.toggleColors(button6));
      let button7 = new import_obsidian.ExtraButtonComponent(nameCellDiv).setIcon("snail").setTooltip("Slowed");
      button7.onClick(() => this.toggleColors(button7));
      let button8 = new import_obsidian.ExtraButtonComponent(nameCellDiv).setIcon("circle-alert").setTooltip("Taunted");
      button8.onClick(() => this.toggleColors(button8));
      let button9 = new import_obsidian.ExtraButtonComponent(nameCellDiv).setIcon("heart-crack").setTooltip("Weakened");
      button9.onClick(() => this.toggleColors(button9));
      tempRow.createEl("td", { text: "stamina", cls: "Centered stamina-Cell trackerTableCellStyle" });
      this.updateStamina(tempRow, creature.CurrentStamina.toString(), creature.Type == "Minion" /* Minion */);
      let buttonCell = tempRow.createEl("td", { cls: green + " trackerTableCellWithMaxWidthStyle max50Width" });
      let buttonComp = new import_obsidian.ExtraButtonComponent(buttonCell);
      buttonComp.extraSettingsEl.setText(no);
      buttonComp.extraSettingsEl.addClass("trackerCellButtonStyle");
      buttonComp.extraSettingsEl.addClass("trackerCellButtonFullHeight");
      buttonComp.onClick(() => {
        this.changeTriggeredActionCell(tempRow, buttonComp, buttonComp.extraSettingsEl.getText() == no);
      });
      let actedButtonCell = tempRow.createEl("td", { cls: green + " trackerTableCellWithMaxWidthStyle max50Width" });
      let actedButtonComp = new import_obsidian.ExtraButtonComponent(actedButtonCell);
      actedButtonComp.extraSettingsEl.setText(no);
      actedButtonComp.extraSettingsEl.addClass("trackerCellButtonStyle");
      actedButtonComp.onClick(() => {
        this.changeActedCell(tempRow, actedButtonComp, actedButtonComp.extraSettingsEl.getText() == no);
      });
      if (creature.Type == "Solo") {
        let secondActedButtonComp = new import_obsidian.ExtraButtonComponent(actedButtonCell);
        secondActedButtonComp.extraSettingsEl.setText(no);
        secondActedButtonComp.extraSettingsEl.addClass("trackerTableCellWithMaxWidthStyle");
        secondActedButtonComp.extraSettingsEl.addClass("trackerCellButtonHalfHeight");
        actedButtonComp.extraSettingsEl.addClass("trackerCellButtonHalfHeight");
        secondActedButtonComp.onClick(() => {
          this.actedButtonTwoClick(tempRow, secondActedButtonComp, secondActedButtonComp.extraSettingsEl.getText() == no);
        });
        actedButtonComp.onClick(() => {
          this.actedButtonOneClick(tempRow, actedButtonComp, actedButtonComp.extraSettingsEl.getText() == no);
        });
      } else {
        actedButtonComp.extraSettingsEl.addClass("trackerCellButtonStyle");
        actedButtonComp.extraSettingsEl.addClass("trackerCellButtonFullHeight");
      }
      buttonCell = tempRow.createEl("td", { cls: "trackerTableRemoveCellStyle max50Width" });
      let removeButton = new import_obsidian.ExtraButtonComponent(buttonCell);
      removeButton.extraSettingsEl.addClass("trackerCellRemoveButtonStyle");
      removeButton.extraSettingsEl.addClass("interactiveColor");
      removeButton.onClick(() => {
        this.removeRow(row);
      });
      buttonCell.createEl("br");
      removeButton.extraSettingsEl.setText("Remove");
    } catch (e) {
      if (e instanceof Error) {
      }
    }
  }
  onHeroTableRowDragStart(event, creature) {
    this.draggedItemIndex = this.heroes.indexOf(creature);
    if (event.dataTransfer != null) {
      event.dataTransfer.dropEffect = "move";
      let jsonCreature = JSON.stringify(creature);
      console.log(jsonCreature);
      event.dataTransfer.setData("text", JSON.stringify(creature));
    }
  }
  onHeroTableRowDragEnter(event, index) {
    if (event.dataTransfer != null) {
      this.heroesTableDragIndex = index;
    }
  }
  onHeroTableRowDragEnd(event) {
  }
  onHeroTableRowDrop(event, creature) {
  }
  toggleColors(ebc) {
    if (ebc.extraSettingsEl.classList.contains("activatedButton")) {
      ebc.extraSettingsEl.removeClass("activatedButton");
    } else {
      ebc.extraSettingsEl.addClass("activatedButton");
    }
  }
  removeRow(row) {
    row.remove();
  }
  updateStamina(row, stamina, isMinion) {
    let staminaCell = row.children[1];
    let parsedId = row.id.split(" ");
    let maxStamina = 0;
    let minionStamina = 0;
    if (parsedId != void 0) {
      if (parsedId[0] == "Hero") {
        maxStamina = this.heroes[+parsedId[1]].MaxStamina;
        minionStamina = this.heroes[+parsedId[1]].MinionStamina;
      } else {
        maxStamina = this.villains[+parsedId[1]].MaxStamina;
        minionStamina = this.villains[+parsedId[1]].MinionStamina;
      }
    }
    staminaCell.empty();
    let staminaDiv = staminaCell.createDiv({ cls: "tableStyle" });
    let header = staminaDiv.createEl("tr");
    if (isMinion) {
      header.createEl("th", { text: ` Max: ${maxStamina} (${minionStamina} per minion)` });
    } else {
      header.createEl("th", { text: ` Max: ${maxStamina}` });
    }
    let bodyCell = staminaDiv.createEl("tr").createEl("td").createDiv({ cls: "centered contents" });
    new import_obsidian.ButtonComponent(bodyCell).setButtonText("-1").onClick(() => {
      this.updateStamina(row, (+stamina - 1).toString(), isMinion);
    });
    let staminaInput = new import_obsidian.TextComponent(bodyCell);
    staminaInput.onChange((value) => {
      stamina = value;
    });
    staminaInput.inputEl.addClasses(["centerText", "max60Width"]);
    staminaInput.setValue(stamina.toString()).inputEl.onkeydown = NumbersOnly;
    new import_obsidian.ButtonComponent(bodyCell).setButtonText("+1").onClick(() => {
      this.updateStamina(row, (+stamina + 1).toString(), isMinion);
    });
  }
  changeActedCell(row, buttonComp, hasActed) {
    if (hasActed) {
      buttonComp.extraSettingsEl.setText(yes);
      row.children[3].addClass(red);
      row.children[3].removeClass(green);
    } else {
      buttonComp.extraSettingsEl.setText(no);
      row.children[3].addClass(green);
      row.children[3].removeClass(red);
    }
  }
  actedButtonOneClick(row, buttonComp, hasActed) {
    this.soloActedButtonClickInner(row, buttonComp, hasActed, 1);
  }
  actedButtonTwoClick(row, buttonComp, hasActed) {
    this.soloActedButtonClickInner(row, buttonComp, hasActed, 0);
  }
  soloActedButtonClickInner(row, buttonComp, hasActed, child) {
    let otherHasActed = row.children[3].children[child].textContent == "Yes";
    if (hasActed) {
      buttonComp.extraSettingsEl.setText(yes);
      if (otherHasActed) {
        row.children[3].addClass(red);
        row.children[3].removeClass(orange);
      } else {
        row.children[3].addClass(orange);
      }
      row.children[3].removeClass(green);
    } else {
      buttonComp.extraSettingsEl.setText(no);
      if (otherHasActed) {
        row.children[3].addClass(orange);
      } else {
        row.children[3].addClass(green);
        row.children[3].removeClass(orange);
      }
      row.children[3].removeClass(red);
    }
  }
  changeTriggeredActionCell(row, buttonComp, hasActed) {
    if (hasActed) {
      buttonComp.extraSettingsEl.setText(yes);
      row.children[2].addClass(red);
      row.children[2].removeClass(green);
    } else {
      buttonComp.extraSettingsEl.setText(no);
      row.children[2].addClass(green);
      row.children[2].removeClass(red);
    }
  }
  newRound(div) {
    let round = ++this.round;
    this.setRound(round, div);
    let malice = this.malice + round + this.heroes.length;
    this.setMalice(malice);
    this.resetActed();
  }
  resetActed() {
    for (let i = 1; i < this.heroesTableEl.children.length; i++) {
      let row = this.heroesTableEl.children[i].children[0].children[0].children[1];
      let button = row.children[2].children[0];
      let triggeredActionButton = row.children[3].children[0];
      button.textContent = no;
      triggeredActionButton.textContent = no;
      row.children[3].removeClass(red);
      row.children[2].removeClass(red);
      row.children[3].addClass(green);
      row.children[2].addClass(green);
    }
    for (let i = 1; i < this.villainsTableEl.children.length; i++) {
      let row = this.villainsTableEl.children[i].children[0].children[0].children[1];
      let button = row.children[2].children[0];
      let triggeredActionButton = row.children[3].children[0];
      button.textContent = no;
      triggeredActionButton.textContent = no;
      row.children[3].removeClass(red);
      row.children[2].removeClass(red);
      row.children[3].addClass(green);
      row.children[2].addClass(green);
    }
  }
  clearHeroesTable() {
    for (let i = 1; i < this.heroesTableEl.children.length; i++) {
      this.heroesTableEl.children[i].remove();
    }
  }
  clearVillainsTable() {
    for (let i = 1; i < this.villainsTableEl.children.length; i++) {
      this.villainsTableEl.children[i].remove();
    }
  }
  openCreateGroupModal() {
    let modal = new import_obsidian.Modal(this.app);
    modal.open();
  }
  allowRename(row, id) {
    var _a;
    let nameField = row.children[1];
    let renameField = row.children[2];
    if (!renameField.hidden) {
      nameField.setText(renameField.value);
    }
    renameField.hidden = !renameField.hidden;
    if (nameField.classList.contains("hideStyle")) {
      nameField.removeClass("hideStyle");
      nameField.addClass("fullWidth");
      nameField.addClass("tableCell");
    } else {
      nameField.addClass("hideStyle");
      nameField.removeClass("fullWidth");
      nameField.removeClass("tableCell");
    }
    if (!renameField.hidden)
      (_a = document.getElementById(id)) == null ? void 0 : _a.focus();
  }
};

// lib/Settings.ts
var DEFAULT_SETTINGS = {
  mySetting: "default",
  playerCharacters: []
};

// lib/main.ts
var ForbiddenLandsCharacterSheet = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.creatures = [];
  }
  async onload() {
    await this.loadSettings();
    this.registerView(
      INITIATIVE_VIEW,
      (leaf) => new InitiativeView(leaf, this.app, this.creatures, this.settings.playerCharacters)
    );
    this.addRibbonIcon("scroll-text", "DRAW STEEL! (Initiative Tracker)", () => {
      this.activateView();
    });
    this.addSettingTab(new RetainerSettingTab(this.app, this));
  }
  onunload() {
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(INITIATIVE_VIEW);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getLeaf(false);
      if (leaf != null)
        await leaf.setViewState({ type: INITIATIVE_VIEW, active: true });
    }
    if (leaf != null)
      workspace.revealLeaf(leaf);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var RetainerSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    let div = containerEl.createDiv({ cls: "rightAlign bottomSpace" });
    new import_obsidian2.ButtonComponent(div).setButtonText("Add player character").setClass("rightAlign").onClick(() => {
      this.buildCharacterInput(containerEl);
    });
    this.plugin.settings.playerCharacters.forEach((x) => this.buildCharacterInput(containerEl, x));
  }
  buildCharacterInput(containerEl, character) {
    let player = character != null ? character : new Creature();
    player.Type = "Hero" /* Hero */;
    if (character == void 0) {
      this.plugin.settings.playerCharacters.push(player);
    }
    let staminaInput = player.MaxStamina == void 0 ? "" : player.MaxStamina.toString();
    let setting = new import_obsidian2.Setting(containerEl).setName("Player character").setDesc("Set the PC's name and stamina").addText((text) => text.setPlaceholder("Name").setValue(player.Name).onChange(async (value) => {
      player.Name = value;
      await this.plugin.saveSettings();
    })).addText((text) => text.setPlaceholder("Stamina").setValue(staminaInput).onChange(async (value) => {
      if (value != null && value != "") {
        player.MaxStamina = +value;
      }
      await this.plugin.saveSettings();
    })).addButton((button) => {
      let b = button.setButtonText("Delete").onClick(async () => {
        this.plugin.settings.playerCharacters.remove(player);
        setting.controlEl.remove();
        setting.nameEl.remove();
        setting.descEl.remove();
        setting.infoEl.remove();
        setting.settingEl.remove();
        await this.plugin.saveSettings();
      });
      return b;
    });
  }
};

/* nosourcemap */